### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by jattig852**

### CODE REVIEW

**Review by anb149 — APPROVED** [review]

**Comment by jattig852** [comment]
The new material doesn't seem to be available on the server.  Could you check what may have happened?

John

**Comment by anb149** [comment]
Hi John,

Thank you so much for informing us. We will take a look and get back to you.

Angel


Angel Peterson (she, her, hers)
Open Publishing Production Specialist
Open Publishing
Research Informatics and Publishing
University Libraries
Penn State University
814-865-2486<tel:8148652486>

[cid:f88ebf03-8ee4-4b5e-a8c9-78a7ac99b97c]

________________________________

**Comment by jattig852** [comment]
I think that the update that you posted last month wasn't available either.

There is an easy way to check.  The home page for the Bibliography
https://openpublishing.psu.edu/locke/bib/index.html
has a date under "Recent Additions to the Bibliography".
I update this just before I do a pull request, so it should always be the current date (almost).
Currently the date is 24 January 2020, so it missed an update in early May as well as the one yesterday.

John

**Comment by AndrewGearhart** [comment]
Hey @jattig852 , sorry for the inconvenience. There was an error in the deployment that is fixed now. Thanks for understanding.

**Pull request merged**
